services:
  frontend:
    build:
      context: .
      dockerfile: DockerfileFront
    ports:
      - "8070:8070"
    restart: always
    networks:
      - finnet
    depends_on:
      - api

  api:
    build: 
      context: .
      dockerfile: DockerfileBack
    ports:
      - "8080:8080"
    restart: always
    networks:
      - finnet

networks:
  finnet:
    driver: bridge